global:
    scrape_interval: 15s
    scrape_timeout: 10s  # افزایش timeout

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'newnextjs-app'
    static_configs:
      - targets: ['172.17.0.1:3000']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/api/metrics'